-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 21:53:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Database Reisa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Database Reisa
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Reisa` DEFAULT CHARACTER SET utf8 ;
USE `Reisa` ;

-- -----------------------------------------------------
-- Table `Reisa`.`Tip_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Tip_User` (
  `ID_Tipo` INT NOT NULL,
  `Descripcion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Usuarios` (
  `NSS` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Fec_Nac` DATE NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contra` VARCHAR(45) NOT NULL,
  `Tip_User` INT NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`NSS`),
  INDEX `tipo_user_idx` (`Tip_User` ASC),
  CONSTRAINT `tipo_user`
    FOREIGN KEY (`Tip_User`)
    REFERENCES `Reisa`.`Tip_User` (`ID_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Reportes` (
  `Folio_Rep` INT NOT NULL AUTO_INCREMENT,
  `Cant_Tic_Aso` INT NOT NULL,
  `Tot_Impo_Tic` INT NOT NULL,
  `User_Crea_Rep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Folio_Rep`),
  INDEX `crea_user_idx` (`User_Crea_Rep` ASC),
  CONSTRAINT `crea_user`
    FOREIGN KEY (`User_Crea_Rep`)
    REFERENCES `Reisa`.`Usuarios` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Tickets` (
  `Folio_Tic` INT NOT NULL AUTO_INCREMENT,
  `Fec_Hor_Crea` DATETIME NOT NULL,
  `Banco_KM` INT NOT NULL,
  PRIMARY KEY (`Folio_Tic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Obras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Obras` (
  `Folio_Ob` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fec_Ini` DATE NOT NULL,
  `Sta_Ob` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Folio_Ob`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Materiales` (
  `ID_Mat` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Mat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`Camiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`Camiones` (
  `Placa` VARCHAR(45) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Costo_Ini` INT NOT NULL,
  `Costo_KM` INT NULL,
  `Material` INT NOT NULL,
  PRIMARY KEY (`Placa`),
  INDEX `material_idx` (`Material` ASC),
  CONSTRAINT `material`
    FOREIGN KEY (`Material`)
    REFERENCES `Reisa`.`Materiales` (`ID_Mat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`User_Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`User_Ticket` (
  `ID_User_Tic` INT NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NOT NULL,
  `TicketID` INT NOT NULL,
  PRIMARY KEY (`ID_User_Tic`, `UserID`, `TicketID`),
  INDEX `fk_Usuarios_has_Tickets_Tickets1_idx` (`TicketID` ASC),
  INDEX `fk_Usuarios_has_Tickets_Usuarios_idx` (`UserID` ASC),
  CONSTRAINT `fk_Usuarios_has_Tickets_Usuarios`
    FOREIGN KEY (`UserID`)
    REFERENCES `Reisa`.`Usuarios` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Tickets_Tickets1`
    FOREIGN KEY (`TicketID`)
    REFERENCES `Reisa`.`Tickets` (`Folio_Tic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`User_Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`User_Obra` (
  `ID_User_Obra` INT NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NOT NULL,
  `ObraID` INT NOT NULL,
  PRIMARY KEY (`ID_User_Obra`, `UserID`, `ObraID`),
  INDEX `fk_Usuarios_has_Obras_Obras1_idx` (`ObraID` ASC),
  INDEX `fk_Usuarios_has_Obras_Usuarios1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Usuarios_has_Obras_Usuarios1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Reisa`.`Usuarios` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Obras_Obras1`
    FOREIGN KEY (`ObraID`)
    REFERENCES `Reisa`.`Obras` (`Folio_Ob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reisa`.`User_Camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reisa`.`User_Camion` (
  `ID_User_Cam` INT NOT NULL AUTO_INCREMENT,
  `UserID` VARCHAR(45) NOT NULL,
  `CamionID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_User_Cam`, `UserID`, `CamionID`),
  INDEX `fk_Usuarios_has_Camiones_Camiones1_idx` (`CamionID` ASC),
  INDEX `fk_Usuarios_has_Camiones_Usuarios1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Usuarios_has_Camiones_Usuarios1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Reisa`.`Usuarios` (`NSS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Camiones_Camiones1`
    FOREIGN KEY (`CamionID`)
    REFERENCES `Reisa`.`Camiones` (`Placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
