
export const FORMULARIO_OBRA = 'FORMULARIO_OBRA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const OBTENER_OBRAS = "OBTENER_OBRAS";
export const AGREGAR_OBRAS = 'AGREGAR_OBRAS';
export const OBRAS_ACTUALES = 'OBRAS_ACTUALES';
export const BORRAR_OBRAS = 'BORRAR_OBRAS';

// aqui llamara a cada prop de las tablas de cada obra y su respectiva configuracion
export const CONFIGURACION_OBRAS = 'CONFIGURACION_OBRAS';
export const AGREGAR_CONFIGURACION = 'AGREGAR_CONFIGURACION';
export const VALIDAR_CONFIGURACION = 'VALIDAR_CONFIGURACION';
export const ELIMINAR_CONFIGURACION = 'ELIMINAR_CONFIGURACION';
export const ESTADO_OBRA = 'ESTADO_OBRA';
export const CONFIGURACION_ACTUAL = 'CONFIGURACION_ACTUAL';
export const ACTUALIZAR_CONFIGURACION = 'ACTUALIZAR_CONFIGURACION';
export const LIMPIAR_CONFIGURACION = 'LIMPIAR_CONFIGURACION'

