
export const FORMULARIO_OBRA = 'FORMULARIO_OBRA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const OBTENER_OBRAS = "OBTENER_OBRAS";
export const AGREGAR_OBRAS = 'AGREGAR_OBRAS';
export const OBRAS_ACTUALES = 'OBRAS_ACTUALES';
export const BORRAR_OBRAS = 'BORRAR_OBRAS';